config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/artists', to: 'artists#index', as: 'artisthome'
  get '/artists/new', to: 'artists#new', as: 'new_artist'
  post '/artists/new', to: 'artists#create'
  get '/artists/:id', to: 'artists#show', as: 'artist'
  get '/artists/:id/edit', to: 'artists#edit', as: 'edit_artist'
  patch '/artists/:id' , to: 'artists#update'
  delete '/artists/:id', to: 'artists#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artist = Artist.all
    end

    def show
        @artist = Artist.find(params[:id])
    end

    def new
        @artist = Artist.new
    end

    def create 
        Artist.create(artist_params)
        redirect_to artisthome_path
    end

    def edit
        @artist = Artist.find(params[:id])
    end

    def update
        @artist = Artist.find(params[:id])
        @artist.update(artist_params)
        redirect_to artist_path
    end

    def destroy
        @artist = Artist.find(params[:id])
        @artist.destroy
        redirect_to artisthome_path
    end

    private 
    def artist_params
        params.require(:artist).permit(:name, :albums, :hometwon, :img)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_for :artist do |f| %>

        <%= f.label :name, 'Name : ' %><br>
        <%= f.text_field :name %><br><br>

        <%= f.label :albums, 'Albums : ' %><br>
        <%= f.text_field :albums %><br><br>

        <%= f.label :hometwon, 'Home Town : ' %><br>
        <%= f.text_field :hometwon %><br><br>

        <%= f.label :img, 'Image :' %><br>
        <%= f.text_field :img  %><br><br>

        <%= f.submit " Save " %>

<% end %>

    <%# <form> %>

        <%# Artist Name:<br>
        <input type='text' name='name'><br> %>
       
        <%# Hometown:<br>
        <input type='text' name='hometwon'><br>
        
        <input type='submit' value='submit'> %>

    <%# </form> %>

app/views/artists/edit.html.erb
<h1> Edit <%= @artist.name %> </h1>

<%= form_for @artist, url: {action: "update"} do |f| %>

        <%= f.label :name, 'Name : ' %><br>
        <%= f.text_field :name %><br><br>

        <%= f.label :albums, 'Albums : ' %><br>
        <%= f.text_field :albums %><br><br>

        <%= f.label :hometwon, 'Home Town : ' %><br>
        <%= f.text_field :hometwon %><br><br>

        <%= f.label :img, 'Image :' %><br>
        <%= f.text_field :img  %><br><br>

        <%= f.submit " Save edits " %>

<% end %>

app/views/artists/index.html.erb
<h1>All the Artists</h1>
<%= link_to 'Add an Artist', new_artist_path%><hr><br>
<% @artist.each do |artist| %>
<tr>
<%# <%= image_tag(artist.img, size: "100x100")><br> %>
<img src=<%= artist.img %> height="100", width="100" ><br>
<td><%= link_to artist.name, artist_path(artist)%></td><br>
<td><%= artist.hometwon %></td><br>
<td><%= artist.albums %></td> <br>
</tr>
<% end %>

<%# <td><%= link_to artist.name, artisthome_path(artist) </td> %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%# <%= render 'artists/form' > %>

<%= form_for @artist , url:{action: "create"} do |f| %>

        <%= f.label :name, 'Name : ' %><br>
        <%= f.text_field :name %><br><br>

        <%= f.label :albums, 'Albums : ' %><br>
        <%= f.text_field :albums %><br><br>

        <%= f.label :hometwon, 'Home Town : ' %><br>
        <%= f.text_field :hometwon %><br><br>

        <%= f.label :img, 'Image :' %><br>
        <%= f.text_field :img  %><br><br>

        <%= f.submit " Save " %>

<% end %>

app/views/artists/show.html.erb
<img src=<%=@artist.img%> height="500", width="500">
<h1><%= @artist.name %> </h1>
<h1>Born in <%= @artist.hometwon %> </h1>
<h1>Albums No.  <%= @artist.albums %> </h1>
<button><%= link_to 'edit', edit_artist_path(@artist) %></button>
<button><%= link_to 'delete', artist_path(@artist), method: :delete %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Muse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>